//
//  ListModels.swift
//  ApiTest
//
//  Created by Андрей Лихачев on 20.10.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List
{
  // MARK: Use cases
  
  enum Models
  {
    struct Request
    {
    }
    struct Response
    {
        let id: String
        let creationDate: Double
        let lastEditDate: Double
        let noteText: String
        
    }
    struct ViewModel
    {
        let id: String
        let creationDate: String
        let lastEditDate: String
        let noteText: String
    }
  }
}
