//
//  ListPresenter.swift
//  ApiTest
//
//  Created by Андрей Лихачев on 20.10.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic
{
}

class ListPresenter: ListPresentationLogic
{
  weak var viewController: ListDisplayLogic?
  
  // MARK: Do something
  
}
