//
//  ListInteractor.swift
//  ApiTest
//
//  Created by Андрей Лихачев on 20.10.2019.
//  Copyright (c) 2019 Андрей Лихачев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic
{
}

protocol ListDataStore
{
  //var name: String { get set }
}

class ListInteractor: ListBusinessLogic, ListDataStore
{
  var presenter: ListPresentationLogic?
  var worker: ListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
}
